"""empty message

Revision ID: d52d40722b4d
Revises: 527ecfcc2c1f
Create Date: 2020-05-13 17:10:43.269669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52d40722b4d'
down_revision = '527ecfcc2c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('app_user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('app_user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('app_user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('app_user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('app_user', 'updated_at')
    op.drop_column('app_user', 'created_at')
    # ### end Alembic commands ###
