"""empty message

Revision ID: e1cd7e7086a3
Revises: 
Create Date: 2020-05-20 19:36:32.274599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cd7e7086a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_category', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('ad_category', 'nodes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_category', sa.Column('nodes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ad_category', 'notes')
    # ### end Alembic commands ###
